### ISSUE TITLE
[bug] crash when trying to set up ssh with public key authentication

### ISSUE THREAD

**Issue by Quantenzitrone** [jazzm0/ssh-daemon#41]
## Stack Trace (Scoop)
```
FATAL EXCEPTION: main
Process: com.daemon.ssh, PID: 13539
java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at s2.b.b(Unknown Source:9)
	at s2.b.a(Unknown Source:52)
	at com.sshdaemon.sshd.SshDaemon.c(Unknown Source:41)
	at com.sshdaemon.MainActivity.onCreate(Unknown Source:114)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2772)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

even if the `authorized_keys` file is wrong, the app should catch the error instead of just crashing

**Comment by jazzm0** [comment]
Can you please post an example authorized_keys file?

**Comment by Quantenzitrone** [comment]
```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGJ0j5BztROLdZYHf8cpJsJr9jd8gCRUfm6oe9k3Bhh0 @quantenzitrone:matrix.org
```
Is what i copied from my VPS server, which works there.

**Comment by J-Siu** [comment]
Same issue. I put SshDaemon folder in the same level as Download, DCIM, etc.

**Comment by Quantenzitrone** [comment]
SHIFT6m with Android 8.1
A "custom" degoogled ROM by the manufacturer if that is important.

**Comment by jazzm0** [comment]
should be fixed with version 2.1.7

**Comment by jazzm0** [comment]
Ok, with https://github.com/jazzm0/ssh-daemon/pull/51/files I removed the apache-codec library, which makes the app slimmer. That should definitely fix this dependency issue. The weird thing is, that this seem to be related to the custom rom, otherwise it would crash on other devices too.

**Comment by jazzm0** [comment]
version 2.1.8 supports already the ssh-ed25519 pubkey auth.

**Comment by Quantenzitrone** [comment]
It doesn't crash, but i can't get my computer to connect:
```
user@<ip>: Permission denied (keyboard-interactive,publickey).
```

If i use password authentication or a rsa keypair instead:
```
Connection to <ip> closed by remote host.
Connection to <ip> closed.
```
My phone closes the connection instantly, maybe that is due to some external reason.

Since it doesn't crash anymore I guess this issue is resolved, I also can't get it to crash if I try and write other stuff into the `authorized_keys` file.
